"use client";

import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { adminApi, categoryApi } from "@/services/platform";
import type { AdminDashboard } from "@/types/platform";
import { EmptyState, Notice, Surface, buttonClass, inputClass } from "@/components/app-ui";

function LoadNotice({ error }: { error: unknown }) {
  return <Notice kind="error" title="Data could not be loaded">{error instanceof Error ? error.message : "Sign in with an authorized account and try again."}</Notice>;
}

export function DashboardData() {
  const query = useQuery({ queryKey: ["admin", "dashboard"], queryFn: adminApi.dashboard });
  if (query.isLoading) return <p aria-live="polite" className="animate-pulse rounded-md bg-muted p-8">Loading dashboard…</p>;
  if (query.isError) return <LoadNotice error={query.error} />;
  if (!query.data) return null;
  const data: AdminDashboard = query.data;
  const values = [["Gross merchandise value", data.summary.grossMerchandizeValue], ["Platform revenue", data.summary.PlatformRevenue], ["Customers", data.summary.registeredCustomerCount], ["Active vendors", data.summary.activeVendorCount]] as const;
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{values.map(([label, value]) => <Surface key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{label === "Customers" || label === "Active vendors" ? value : Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value)}</p></Surface>)}</div>;
}

export function CategoryManager() {
  const qc = useQueryClient(); const query = useQuery({ queryKey: ["admin", "categories"], queryFn: categoryApi.list });
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function createCategory(data: FormData) { setPending(true); setMessage(""); try { await categoryApi.create({ name: String(data.get("name") ?? "").trim(), parentCategory: String(data.get("parentCategory") ?? "").trim() || undefined, attributes: String(data.get("attributes") ?? "").split(",").map((part) => part.trim()).filter(Boolean) }); await qc.invalidateQueries({ queryKey: ["admin", "categories"] }); toast.success("Category created"); } catch (error) { setMessage(error instanceof Error ? error.message : "Category creation failed."); } finally { setPending(false); } }
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><Surface><h2 className="text-lg font-semibold">Categories</h2>{query.isLoading && <p className="mt-4 text-sm text-muted-foreground">Loading categories…</p>}{query.isError && <div className="mt-4"><LoadNotice error={query.error} /></div>}{query.data && (query.data.categories.length ? <ul className="mt-4 divide-y divide-border">{query.data.categories.map((category) => <li key={category._id} className="flex min-h-14 items-center justify-between gap-3 py-3"><div><p className="font-medium">{category.name}</p><p className="mt-1 text-xs text-muted-foreground">{typeof category.parentCategory === "object" && category.parentCategory ? `Parent: ${category.parentCategory.name}` : "Top-level category"}</p></div><div className="flex items-center gap-3"><span className="hidden text-xs text-muted-foreground sm:inline">{category.attributes?.length ?? 0} attributes</span><button type="button" disabled title="Category deletion is unavailable in the backend" aria-label={`Delete ${category.name} category unavailable`} className="min-h-11 rounded-md border border-border px-3 text-xs opacity-50">Delete</button></div></li>)}</ul> : <EmptyState title="No categories yet" detail="Create the first marketplace category." />)}</Surface><Surface><h2 className="text-lg font-semibold">Create category</h2><form action={createCategory} className="mt-4 space-y-4"><FormField name="name" label="Category name" required /><label className="block space-y-1.5 text-sm font-medium">Parent category<select name="parentCategory" defaultValue="" className={inputClass}><option value="">No parent</option>{query.data?.categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></label><FormField name="attributes" label="Attributes (comma separated)" /><p className="text-xs leading-5 text-muted-foreground">Category deletion is unavailable because the backend route is malformed.</p>{message && <p role="alert" className="text-sm text-destructive">{message}</p>}<button className={buttonClass} disabled={pending}>{pending ? "Creating…" : "Create category"}</button></form></Surface></div>;
}

export function VendorApplications() {
  const [status, setStatus] = useState("pending"); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const qc = useQueryClient();
  const query = useQuery({ queryKey: ["admin", "vendors", page, status], queryFn: () => adminApi.vendors(page, status) });
  async function approve(id: string, userId: string) { if (!window.confirm("Approve this vendor application? This will activate the vendor account.")) return; try { await adminApi.approveVendor(id, userId); toast.success("Vendor approved"); await qc.invalidateQueries({ queryKey: ["admin", "vendors"] }); } catch (error) { toast.error(error instanceof Error ? error.message : "Approval failed"); } }
  const filteredVendors = query.data?.vendors.filter((vendor) => `${vendor.companyName} ${vendor.name} ${vendor.lastName} ${typeof vendor.userid === "string" ? "" : vendor.userid.email}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><label className="text-sm font-medium">Application status<select className={`${inputClass} mt-1`} value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="pending">Pending</option><option value="active">Approved</option></select></label><label className="w-full max-w-sm space-y-1.5 text-sm font-medium">Search this page<input className={inputClass} placeholder="Business, owner, or email" value={search} onChange={(event) => setSearch(event.target.value)} /></label></div><Surface className="overflow-hidden p-0">{query.isLoading && <p className="p-6 text-sm text-muted-foreground">Loading vendor applications…</p>}{query.isError && <div className="p-5"><LoadNotice error={query.error} /></div>}{query.data && query.data.vendors.length === 0 && <EmptyState title="No vendor applications" detail={`There are no ${status} vendors on this page.`} />}{query.data && filteredVendors.length === 0 && query.data.vendors.length > 0 && <EmptyState title="No matching vendors" detail="Try another business, owner, or email search." />}{query.data && filteredVendors.length > 0 && <div className="divide-y divide-border">{filteredVendors.map((vendor) => { const userId = typeof vendor.userid === "string" ? vendor.userid : vendor.userid._id; const email = typeof vendor.userid === "string" ? "" : vendor.userid.email; return <article key={vendor._id} className="flex flex-wrap items-center justify-between gap-4 p-4 sm:p-5"><div><h2 className="font-semibold">{vendor.companyName}</h2><p className="mt-1 text-sm text-muted-foreground">{vendor.name} {vendor.lastName} · {email} · {vendor.country}</p></div><div className="flex items-center gap-3"><span className="text-xs capitalize text-muted-foreground">{vendor.status}</span>{status === "pending" && <button onClick={() => void approve(vendor._id, userId)} className="min-h-11 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Approve</button>}</div></article>; })}</div>}</Surface><Pagination page={page} setPage={setPage} pages={query.data?.totalPages ?? 1} /></>;
}

export function AdminOrders() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const query = useQuery({ queryKey: ["admin", "orders", page], queryFn: () => adminApi.orders(page) });
  if (query.isLoading) return <p className="animate-pulse rounded bg-muted p-8">Loading orders…</p>;
  if (query.isError) return <LoadNotice error={query.error} />;
  if (!query.data) return null;
  const filtered = query.data.orders.filter((order) => `${order._id} ${order.customerID?.name ?? ""} ${order.customerID?.email ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  if (!query.data.orders.length) return <Surface><EmptyState title="No orders found" detail="Orders will appear here when customers place them." /></Surface>;
  return <><label className="mb-4 block max-w-sm space-y-1.5 text-sm font-medium">Search this page<input className={inputClass} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Order ID or customer" /></label><Surface className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Order", "Customer", "Total", "Payment", "Date"].map((title) => <th key={title} className="px-5 py-4 font-medium">{title}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map((order) => <tr key={order._id}><td className="px-5 py-4 font-medium">{order._id.slice(-8)}</td><td className="px-5 py-4">{order.customerID?.name ?? order.customerID?.email ?? "Customer details unavailable"}</td><td className="px-5 py-4">{typeof order.totalPrice === "number" ? cash(order.totalPrice) : "—"}</td><td className="px-5 py-4 capitalize">{order.paymentStatus ?? "—"}</td><td className="px-5 py-4 text-muted-foreground">{order.createdAt ? new Date(order.createdAt).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">No orders match this page search.</p>}</Surface><Pagination page={page} setPage={setPage} pages={query.data.totalPages} /></>;
}

export function AdminBalances() {
  const [page, setPage] = useState(1); const query = useQuery({ queryKey: ["admin", "balances", page], queryFn: () => adminApi.balances(page) });
  if (query.isLoading) return <p className="animate-pulse rounded bg-muted p-8">Loading balance ledger…</p>;
  if (query.isError) return <LoadNotice error={query.error} />;
  if (!query.data) return null;
  const rows = query.data.vendorsData;
  if (!rows.length) return <Surface><EmptyState title="No balance entries" detail="There are no vendor balance records in this ledger." /></Surface>;
  return <><Surface className="overflow-x-auto p-0"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Vendor", "Gross sales", "Vendor balance", "Platform revenue"].map((item) => <th key={item} className="px-5 py-4 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((item) => <tr key={item.vendorID}><td className="px-5 py-4 font-medium">{item.BusinessName}</td><td className="px-5 py-4">{cash(item.grossSales)}</td><td className="px-5 py-4">{cash(item.vendorPayoutBalance)}</td><td className="px-5 py-4">{cash(item.platfromRevenue)}</td></tr>)}</tbody></table></Surface><Pagination page={page} setPage={setPage} pages={query.data.totalPages} /></>;
}

export function BlockedProducts() { return <div className="space-y-5"><Notice title="Product feed is unavailable">The admin product endpoint has backend implementation errors. Product records are not fabricated, and moderation actions remain disabled.</Notice><Surface><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input disabled aria-label="Search products" placeholder="Search products" className={inputClass} /><select disabled aria-label="Filter by status" className={inputClass}><option>All statuses</option><option>Active</option><option>Pending review</option></select><select disabled aria-label="Filter by category" className={inputClass}><option>All categories</option></select><button type="button" disabled className="min-h-11 rounded-md border border-border text-sm opacity-50">Apply filters</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-y border-border text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Product", "Vendor", "Category", "Price", "Stock", "Status"].map((label) => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody><tr><td colSpan={6} className="px-3 py-12 text-center text-muted-foreground">Product management will be populated when the backend feed is repaired.</td></tr></tbody></table></div></Surface></div>; }

function FormField({ name, label, required }: { name: string; label: string; required?: boolean }) { return <label className="block space-y-1.5 text-sm font-medium">{label}<input name={name} className={inputClass} required={required} /></label>; }
function Pagination({ page, pages, setPage }: { page: number; pages: number; setPage: (page: number) => void }) { return <div className="mt-4 flex items-center justify-between"><button className="min-h-11 rounded-md border border-border px-4 text-sm disabled:opacity-50" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><p className="text-sm text-muted-foreground">Page {page} of {Math.max(1, pages)}</p><button className="min-h-11 rounded-md border border-border px-4 text-sm disabled:opacity-50" disabled={page >= pages} onClick={() => setPage(page + 1)}>Next</button></div>; }
function cash(value: number) { return Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }
