"use client";

import Link from "next/link";
import Image from "next/image";
import { useQuery } from "@tanstack/react-query";
import { Store, Package, WalletCards, ShoppingCart, Plus, Search } from "lucide-react";
import { vendorApi } from "@/services/platform";
import { BlockedNotice, EmptyState, Notice, Surface, inputClass } from "@/components/app-ui";

export function VendorOverview() {
  const query = useQuery({ queryKey: ["vendor", "profile"], queryFn: vendorApi.profile });
  return <div className="space-y-6"><section><p className="text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground">Seller workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Store overview</h1><p className="mt-3 text-sm text-muted-foreground">Manage your store and review marketplace activity.</p></section>{query.isLoading && <p className="animate-pulse rounded-md bg-muted p-6">Loading store profile…</p>}{query.isError && <Notice kind="error" title="Store profile could not be loaded">{query.error instanceof Error ? query.error.message : "Sign in with a vendor account to continue."}</Notice>}{query.data && <Surface><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-muted-foreground">Store</p><h2 className="mt-1 text-xl font-semibold">{query.data.vendor.companyName}</h2><p className="mt-1 text-sm text-muted-foreground">{query.data.vendor.storeSlug}</p></div><Link href="/vendor/profile" className="min-h-11 rounded-md border border-border px-4 py-3 text-sm">View profile</Link></div></Surface>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ShoppingCart} title="Orders" detail="Order reporting is temporarily unavailable." href="/vendor/orders" /><Metric icon={Package} title="Products" detail="Product management is not connected yet." href="/vendor/products" /><Metric icon={Store} title="Inventory" detail="Inventory reporting is temporarily unavailable." href="/vendor/inventory" /><Metric icon={WalletCards} title="Finance" detail="Finance reporting is temporarily unavailable." href="/vendor/finance" /></div><BlockedNotice title="Vendor metrics unavailable" detail="The vendor orders, inventory, and finance endpoints have backend errors. No sample figures are shown." /></div>;
}

export function VendorProfile() {
  const query = useQuery({ queryKey: ["vendor", "profile"], queryFn: vendorApi.profile });
  if (query.isLoading) return <p className="animate-pulse rounded-md bg-muted p-8">Loading profile…</p>;
  if (query.isError) return <Notice kind="error" title="Store profile could not be loaded">{query.error instanceof Error ? query.error.message : "Sign in using the vendor account connected to this store."}</Notice>;
  if (!query.data) return null;
  const store = query.data.vendor;
  const rows: [string, string][] = [["Business name", store.companyName], ["Store owner", `${store.name} ${store.lastName}`], ["Country", store.country], ["Contact number", store.mobilenumber], ["Store slug", store.storeSlug], ["Status", store.status]];
  return <div className="grid gap-6 md:grid-cols-[220px_1fr]"><Surface className="relative grid min-h-48 place-items-center bg-muted/40">{store.Companyimage?.cloudinaryId ? <Image src={store.Companyimage.cloudinaryId} alt={`${store.companyName} store`} fill unoptimized sizes="220px" className="object-contain p-4" /> : <Store aria-hidden="true" size={42} className="text-muted-foreground" />}</Surface><Surface><h2 className="text-lg font-semibold">Store information</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value || "Not provided"}</dd></div>)}</dl><div className="mt-5 border-t border-border pt-4"><h3 className="text-xs uppercase tracking-wide text-muted-foreground">Description</h3><p className="mt-2 text-sm leading-6">{store.storeDescription || "No description provided."}</p></div><p className="mt-5 text-xs text-muted-foreground">Store profile editing is not supported by the current backend API.</p></Surface></div>;
}

export function VendorBlockedPage({ title, detail }: { title: string; detail: string }) { return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground">Seller workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1></div><Surface><EmptyState title="This area is ready for your store" detail={detail} /></Surface></div>; }

export function VendorInventoryPanel() { return <div className="space-y-5"><PageIntro title="Inventory" detail="Monitor stock levels and find products that need attention." /><BlockedNotice title="Inventory data is unavailable" detail="The backend logistics endpoint currently has implementation errors. Inventory records and quantities are not fabricated." /><Surface><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><label className="relative"><span className="sr-only">Search inventory</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input disabled className={`${inputClass} pl-9`} placeholder="Search inventory" /></label><select disabled className={inputClass} aria-label="Filter inventory by stock"><option>All stock levels</option><option>Low stock</option><option>Healthy</option></select></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-y border-border text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Product", "SKU", "Category", "Stock", "Status"].map((label) => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody><tr><td colSpan={5} className="px-3 py-12 text-center text-muted-foreground">Inventory list will appear when the backend route is repaired.</td></tr></tbody></table></div></Surface></div>; }

export function VendorOrdersPanel() { return <div className="space-y-5"><PageIntro title="Orders" detail="Review incoming orders and their fulfillment status." /><BlockedNotice title="Order records are unavailable" detail="The vendor order endpoint currently fails in the backend, and its status mutation route has no order ID parameter." /><Surface><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><label className="relative"><span className="sr-only">Search vendor orders</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input disabled className={`${inputClass} pl-9`} placeholder="Search orders" /></label><select disabled className={inputClass} aria-label="Filter orders by status"><option>All statuses</option><option>Processing</option><option>Shipped</option><option>Delivered</option></select></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-y border-border text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Order", "Customer", "Items", "Total", "Status", "Date"].map((label) => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody><tr><td colSpan={6} className="px-3 py-12 text-center text-muted-foreground">Vendor orders will appear when the service is available.</td></tr></tbody></table></div></Surface></div>; }

export function VendorFinancePanel() { return <div className="space-y-5"><PageIntro title="Finance" detail="Track revenue, earnings, and marketplace transactions." /><BlockedNotice title="Finance data is unavailable" detail="The vendor finance endpoint currently has implementation errors. No sample revenue values are shown." /><div className="grid gap-4 sm:grid-cols-3">{["Gross sales", "Vendor earnings", "Transactions"].map((title) => <Surface key={title}><p className="text-sm text-muted-foreground">{title}</p><p className="mt-3 text-2xl font-semibold text-muted-foreground">—</p></Surface>)}</div><Surface><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Revenue over time</h2><select disabled className="min-h-11 rounded-md border border-input bg-background px-3 text-sm" aria-label="Chart time range"><option>Last 6 months</option><option>Last year</option></select></div><div className="mt-5 grid h-52 place-items-center rounded-md border border-dashed border-border text-sm text-muted-foreground">Revenue chart appears when the finance service is fixed.</div></Surface><Surface><h2 className="font-semibold">Transactions</h2><p className="mt-2 text-sm text-muted-foreground">Transaction history is not available yet.</p></Surface></div>; }

export function VendorProductPanel() { return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><PageIntro title="Products" detail="Manage product listings and stock details for your store." /><button type="button" disabled title="Product creation is unavailable until the backend route is repaired" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground opacity-50"><Plus size={16} />Add product</button></div><BlockedNotice title="Product management is disabled" detail="The backend create, read, update, and delete product routes are currently blocked. No product changes can be submitted." /><Surface><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><label className="relative"><span className="sr-only">Search products</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input disabled className={`${inputClass} pl-9`} placeholder="Search products" /></label><select disabled className={inputClass} aria-label="Filter products"><option>All product status</option><option>Active</option><option>Pending review</option></select></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-y border-border text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Product", "Category", "Price", "Stock", "Status"].map((label) => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody><tr><td colSpan={5} className="px-3 py-12 text-center text-muted-foreground">Product listings will appear when vendor product APIs are repaired.</td></tr></tbody></table></div></Surface></div>; }

function PageIntro({ title, detail }: { title: string; detail: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground">Seller workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{detail}</p></div>; }

function Metric({ icon: Icon, title, detail, href }: { icon: typeof Store; title: string; detail: string; href: string }) { return <Link href={href} className="rounded-lg border border-border bg-card p-5 transition-colors hover:bg-muted/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Icon size={19} aria-hidden="true" className="text-muted-foreground" /><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-5 text-muted-foreground">{detail}</p></Link>; }
